### ISSUE TITLE
Refactor common code out of workflow scripts

### ISSUE THREAD

**Issue by ncollier** [ECP-CANDLE/Supervisor#20]
The workflow scripts contain a lot of duplicated code that can be removed and put in a single place such as Supervisor/common/sh.

**Comment by jmjwozniak** [comment]
I would like to help with this.  I am starting a README for discussion here: https://github.com/ECP-CANDLE/Supervisor/blob/master/workflows/common/sh/README.adoc

**Comment by jmjwozniak** [comment]
Work for this is proceeding in branch issue-22.

**Comment by jmjwozniak** [comment]
Done- we are down to a single mlrMBO directory.
