### ISSUE TITLE
Swift whitespace conventions

### ISSUE THREAD

**Issue by jmjwozniak** [ECP-CANDLE/Supervisor#27]
Need to determine convention for Swift scripts, such as indentation level and opening brace position.  @ncollier , any preferences?

**Comment by ncollier** [comment]
I'd prefer opening brace on the same line and indentation of 4 spaces. That said, I don't feel strongly about it. I think the emews template produced code isn't consistent here, so I should fix that.

**Comment by jmjwozniak** [comment]
Ok we will do that.
