### ISSUE TITLE
model_runner.py model naming convention

### ISSUE THREAD

**Issue by ncollier** [ECP-CANDLE/Supervisor#33]
From Tom B.

when you get a chance, can you look at model_runner.py not dependent on the the naming convention, particularly:
module_name = "{}_baseline_keras2".format(model_name)
Not sure how best to do it.
but it really locks us into a directory and naming convention
say I have ...Combo/infer.py that I want to run using the UPF workflow
I can name it Combo/infer_baseline_keras.py but the current use of MODEL_NAME assumes the directory and the first part of the model name are the same.

**Comment by jmjwozniak** [comment]
I can do this- I plan to simply allow the user to set an environment variable OBJ_FILE that will substitute that file for obj_app.swift in workflow.sh .  This will give the user the opportunity to implement this interface: 

(string obj_result) obj(string params, string run_id) 

which is pretty generic, and will be totally compatible with CANDLE.

**Comment by jmjwozniak** [comment]
This is basically done but there is some code left over that handles MODEL_NAME and MODEL_SH that needs to be reformatted.  After this issue, MODEL_NAME and MODEL_SH are only required when using the CANDLE obj_app module- other OBJ_MODULE choices do not need these settings (but users can set their own environment variables, of course).

**Comment by brettin** [comment]
If I understand this, you want OBJ_FILE to be swift code. Is this correct?

**Comment by jmjwozniak** [comment]
Ah- OBJ_FILE was my original idea.  I split this into OBJ_DIR and OBJ_MODULE as in the docs.

**Comment by hyoo** [comment]
You can modify OBJ_FILE (in swift code) for more complicated behavior change. In addition to that, if you want to call a python of your interest, you can set MODEL_PYTHON_SCRIPT. see https://github.com/ECP-CANDLE/Supervisor/commit/653eda0df1c283783fae1d36852b8bd22dc60023 for example.

see here for more implementation detail,
https://github.com/ECP-CANDLE/Supervisor/commit/11a295f99ca49aac3103f4d9ad6f4df607655883#diff-b3edd784c76dc5e80070d43a2d948cdbR19
