### ISSUE TITLE
Example of calling infer using OBJ_MODULE 

### ISSUE THREAD

**Issue by jmjwozniak** [ECP-CANDLE/Supervisor#34]
Use #33 to call infer without the need for a soft link at infer_baseline_keras2.py .

**Comment by brettin** [comment]
Questions:
OBJ_FILE contains only the name.
The PATH is updated in langs-app-<machine>.sh
The PYTHON path is updated in langs-apps-<machine>.sh

**Comment by jmjwozniak** [comment]
Can you point me to where you are looking at OBJ_FILE?
