### ISSUE TITLE
Draft Challenge Problem -formatted workflow

### ISSUE THREAD

**Issue by jmjwozniak** [ECP-CANDLE/Supervisor#46]
Draft workflow that uses S[1-5].py to inject user code.

**Comment by brettin** [comment]
[CANDLE Exascale Challenge Problem Pilot 1 - working copy.docx](https://github.com/ECP-CANDLE/Supervisor/files/2616792/CANDLE.Exascale.Challenge.Problem.Pilot.1.-.working.copy.docx)

The above is the current version of the challenge problem description. I will try to post updates. Let me know if there is a better place to keep the most current version.
