### ISSUE TITLE
TURBINE_LAUNCH_OPTIONS

### ISSUE THREAD

**Issue by hyoo** [ECP-CANDLE/Supervisor#68]
https://github.com/ECP-CANDLE/Supervisor/blob/develop/workflows/common/sh/env-summit.sh#L37

for summit, it is hardcoded and ignore user's setting. 

Can we preserve what users set, and give default value when it is empty?

**Comment by jmjwozniak** [comment]
See #67 .  We need to make it more clear that we are using branch develop.  I can merge #67 to develop.

**Comment by hyoo** [comment]
no i was referring `env-summit.sh` where we hardcode `-g6 -c42 -a1`

**Comment by jmjwozniak** [comment]
This is no longer in env-summit, it is in cp-leaveout/test/cfg-sys-512.sh as an example usage.
